"""
CrewAI agent crew for the Drug Interaction Checker.

Agent roles
-----------
1. Interaction Researcher   - gathers candidate interactions from the tool.
2. Clinical Interaction Analyst - ranks/explains the risks for THIS patient.
3. Safety Report Writer      - drafts the clear, patient-friendly report.
4. Safety Reviewer          - verifies the disclaimer + tones down any
                              language that could be read as medical advice.

The OpenAI Agents SDK is used as the orchestration/runtime surface; CrewAI
defines the agent roles and their collaboration.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from app.tools.interaction_tool import DRUG_TOOL, lookup_interactions

DISCLAIMER = (
    "DISCLAIMER: This report is generated by an automated demonstration agent "
    "and is NOT medical advice. It does not replace consultation with a "
    "qualified healthcare professional or a verified clinical database. "
    "Always confirm with your doctor or pharmacist before changing, starting, "
    "or stopping any medication."
)


# ---------------------------------------------------------------------------
# Structured outputs
# ---------------------------------------------------------------------------
class SafetyReport(BaseModel):
    patient_medications: list[str] = Field(default_factory=list)
    overall_risk: str = Field(
        description="One of: low, moderate, high, contraindicated"
    )
    findings: list[dict[str, Any]] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    unrecognised_medications: list[str] = Field(default_factory=list)
    disclaimer: str = DISCLAIMER


# ---------------------------------------------------------------------------
# CrewAI crew (lazy import so the app still imports without crewai installed)
# ---------------------------------------------------------------------------
def build_crew(model: str = "gpt-4o-mini"):
    """Build and return a CrewAI Crew. Returns None if crewai is unavailable."""
    try:
        from crewai import Agent, Crew, Process, Task
    except Exception as e:  # pragma: no cover
        print(f"[crew] crewai not available: {e}")
        return None

    tool = DRUG_TOOL if DRUG_TOOL is not None else None
    tools = [tool] if tool is not None else []

    researcher = Agent(
        role="Interaction Researcher",
        goal="Retrieve every candidate dangerous interaction for the patient's medication list using the lookup tool.",
        backstory=(
            "A meticulous pharmacology researcher who never misses a pair and "
            "always cites the mechanism from the knowledge base."
        ),
        tools=tools,
        verbose=False,
        allow_delegation=False,
    )

    analyst = Agent(
        role="Clinical Interaction Analyst",
        goal="Rank the interactions by severity for THIS patient and explain the real-world risk.",
        backstory=(
            "A clinical pharmacist who translates pharmacology into plain, "
            "prioritised risk for a lay reader."
        ),
        verbose=False,
        allow_delegation=False,
    )

    writer = Agent(
        role="Safety Report Writer",
        goal="Produce a clear, structured, patient-friendly safety report from the analysis.",
        backstory=(
            "A health communicator who writes calm, actionable summaries "
            "without alarming language."
        ),
        verbose=False,
        allow_delegation=False,
    )

    reviewer = Agent(
        role="Safety Reviewer",
        goal="Ensure the disclaimer is present and that no sentence implies personal medical advice.",
        backstory=(
            "A compliance reviewer who guards against overconfident or "
            "advisory language and insists on the not-medical-advice notice."
        ),
        verbose=False,
        allow_delegation=False,
    )

    research_task = Task(
        description=(
            "Use the drug_interaction_lookup tool on the patient's medication "
            "list: {medications}. Return all retrieved candidate interactions."
        ),
        expected_output="A list of candidate interactions with severities.",
        agent=researcher,
    )

    analysis_task = Task(
        description=(
            "Review the candidate interactions and rank them by severity for "
            "this patient. Identify the overall risk level and the top concerns."
        ),
        expected_output="A prioritised risk assessment and overall_risk level.",
        agent=analyst,
        context=[research_task],
    )

    writing_task = Task(
        description=(
            "Write a patient-friendly safety report with findings and "
            "recommendations based on the analysis."
        ),
        expected_output="A structured safety report (markdown).",
        agent=writer,
        context=[analysis_task],
    )

    review_task = Task(
        description=(
            "Verify the disclaimer is included and tone down any language that "
            "could be read as personal medical advice. Return final report."
        ),
        expected_output="The final, compliant safety report.",
        agent=reviewer,
        context=[writing_task],
    )

    crew = Crew(
        agents=[researcher, analyst, writer, reviewer],
        tasks=[research_task, analysis_task, writing_task, review_task],
        process=Process.sequential,
        verbose=False,
    )
    return crew


# ---------------------------------------------------------------------------
# Fallback: deterministic report when the LLM/crew is unavailable
# (keeps the demo working offline with no API calls)
# ---------------------------------------------------------------------------
def build_report_offline(medications: list[str]) -> SafetyReport:
    result = lookup_interactions(medications)
    order = {"contraindicated": 0, "high": 1, "moderate": 2, "low": 3}
    sev_to_risk = {
        "contraindicated": "contraindicated",
        "high": "high",
        "moderate": "moderate",
        "low": "low",
    }
    overall = "low"
    if result.interactions:
        top = min(result.interactions, key=lambda h: order.get(h.severity, 9))
        overall = sev_to_risk.get(top.severity, "moderate")

    findings = [
        {
            "drug_a": h.drug_a,
            "drug_b": h.drug_b,
            "severity": h.severity,
            "mechanism": h.mechanism,
            "management": h.management,
        }
        for h in result.interactions
    ]

    recs = []
    if result.interactions:
        recs.append(
            "Discuss the flagged combinations with your doctor or pharmacist "
            "before making any changes."
        )
        for h in result.interactions:
            if h.severity in ("contraindicated", "high"):
                recs.append(f"Priority: review {h.drug_a} + {h.drug_b} ({h.severity}).")
    else:
        recs.append(
            "No known dangerous interactions were found in the demo knowledge "
            "base for the recognised medications."
        )
    if result.unknown_drugs:
        recs.append(
            "Verify these names with a clinician, as they were not recognised: "
            + ", ".join(result.unknown_drugs)
        )

    return SafetyReport(
        patient_medications=result.found_drugs,
        overall_risk=overall,
        findings=findings,
        recommendations=recs,
        unrecognised_medications=result.unknown_drugs,
    )


__all__ = [
    "DISCLAIMER",
    "SafetyReport",
    "build_crew",
    "build_report_offline",
    "lookup_interactions",
]
